import { test, expect } from '@playwright/test';

/**
 * Login Test - Valid Credentials
 * Test successful login with valid credentials.
 * 
 * Flow Type: authentication
 * Priority: 1
 * Tags: @auth @functional
 * 
 * Generated by LevelUp AI QA Engine
 * Base URL: https://www.saucedemo.com/
 */

test.describe('Login Test - Valid Credentials', () => {
  const consoleErrors: string[] = [];

  test.beforeEach(async ({ page }) => {
    // Capture console errors
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
  });

  test.afterEach(async () => {
    consoleErrors.length = 0;
  });

  test('Test successful login with valid credentials.', async ({ page }) => {
    // Step 1: Navigate to the login page.
    await page.goto(process.env.BASE_URL || 'login page');
    await page.waitForLoadState('domcontentloaded');
    await page.waitForLoadState('domcontentloaded')
    await expect(page).toHaveTitle(/.+/)

    // Step 2: Fill in the username input with valid username.
    await page.getByRole('textbox', { name: /username input/i }).fill('' + (process.env.USERNAME || 'Admin') + '');

    // Step 3: Fill in the password input with valid password.
    await page.getByRole('textbox', { name: /password input/i }).fill('' + (process.env.PASSWORD || 'admin123') + '');

    // Step 4: Click on the login button.
    await page.getByRole('button', { name: /login button/i }).click();
    await Promise.race([
      page.waitForNavigation({ waitUntil: 'domcontentloaded', timeout: 10000 }),
      page.waitForResponse(resp => resp.status() < 400, { timeout: 10000 }),
    ]).catch(() => {})
    await expect(page).not.toHaveURL(/login|signin/i)
    await expect(page.locator('h1, h2, .welcome, .dashboard, [class*="dashboard"]').first()).toBeVisible({ timeout: 10000 })

    // Step 5: Verify that the user is redirected to the Products page.
    // Assert: Verify that the user is redirected to the Products page.

    // Step 6: Verify that the list of available products is displayed.
    // Assert: Verify that the list of available products is displayed.
  });


  test('should show error with invalid credentials', async ({ page }) => {
    await page.goto(process.env.BASE_URL || 'https://www.saucedemo.com/');
    await page.waitForLoadState('domcontentloaded');

    // Fill with invalid credentials
    const usernameField = page.locator('input[type="text"], input[type="email"], input[name*="user" i], input[name*="email" i]').first();
    const passwordField = page.locator('input[type="password"]').first();
    const submitBtn = page.locator('button[type="submit"], input[type="submit"], button:has-text("Login"), button:has-text("Sign")').first();

    await usernameField.fill('invalid_user');
    await passwordField.fill('wrong_password');
    await submitBtn.click();

    // Should show error and stay on login page
    await expect(page.locator('.error, .alert-danger, [role="alert"], .oxd-alert, .invalid-feedback').first()).toBeVisible({ timeout: 5000 });
    await expect(page).toHaveURL(/login|signin/i);
  });

  test('should show validation for empty fields', async ({ page }) => {
    await page.goto(process.env.BASE_URL || 'https://www.saucedemo.com/');
    await page.waitForLoadState('domcontentloaded');

    // Click submit without filling fields
    const submitBtn = page.locator('button[type="submit"], input[type="submit"], button:has-text("Login"), button:has-text("Sign")').first();
    await submitBtn.click();

    // Should show validation or stay on page
    await expect(page).toHaveURL(/login|signin/i);
  });

});