import { test, expect } from '@playwright/test';

/**
 * Smoke Test - Swag Labs
 * Basic smoke test to verify the main page title.
 * 
 * Flow Type: smoke
 * Priority: 1
 * Tags: @smoke
 * 
 * Generated by LevelUp AI QA Engine
 * Base URL: https://www.saucedemo.com/
 */

test.describe('Smoke Test - Swag Labs', () => {
  const consoleErrors: string[] = [];

  test.beforeEach(async ({ page }) => {
    // Capture console errors
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });
  });

  test.afterEach(async () => {
    consoleErrors.length = 0;
  });

  test('Basic smoke test to verify the main page title.', async ({ page }) => {
    // Step 1: Navigate to the main page of Swag Labs.
    await page.goto(process.env.BASE_URL || 'main page');
    await page.waitForLoadState('domcontentloaded');
    await page.waitForLoadState('domcontentloaded')
    await expect(page).toHaveTitle(/.+/)

    // Step 2: Verify that the page title is 'Swag Labs'.
    // Assert: Verify that the page title is 'Swag Labs'.
  });


});