import { test, expect } from '@playwright/test';

/**
 * Verify concurrent login attempts with valid credentials
 *
 * Test Case ID: 1222
 * Priority: P2
 * Coverage: n/a
 * Steps:
   *   1. Open two browser instances
   *   2. In both instances, navigate to https://www.saucedemo.com
   *   3. In the first instance, enter valid username from valid_users: standard_user and valid password placeholder <password>
   *   4. In the second instance, enter valid username from valid_users: standard_user and valid password placeholder <password>
   *   5. Click the login button in both instances
 * Expected Result: Both instances should log in successfully without errors.
 * Test Data: standard_user from valid_users
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com
 */

test.describe('Verify concurrent login attempts with valid credentials', () => {
  test('Verify concurrent login attempts with valid credentials', async ({ page }) => {
  // @tc:TC1222
    // Open two browser instances
    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    
    // In both instances, navigate to https://www.saucedemo.com
    // NOTE: step not auto-mapped — review manually.
    
    // In the first instance, enter valid username from valid_users: standard_user and valid password placeholder <password>
    await page.locator('#user-name').fill('');
    
    // In the second instance, enter valid username from valid_users: standard_user and valid password placeholder <password>
    await page.locator('#user-name').fill('');
    
    // Click the login button in both instances
    await page.locator('#login-button').click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page).not.toHaveURL('https://www.saucedemo.com');
  });
});