import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../pages/LoginPage';
import { InventoryPage } from '../pages/InventoryPage';

/**
 * Verify navigation to Inventory page after successful login
 *
 * Test Case ID: 1217
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Verify that the URL is https://www.saucedemo.com/inventory.html
   *   2. Check that the Inventory page elements are displayed
 * Expected Result: User is on the Inventory page.
 * Test Data: standard_user from valid_users
 * Test Data Source: dataset "valid_users" (representative record, runtime-resolved) (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com/
 */

test.describe('Verify navigation to Inventory page after successful login', () => {
  test('Verify navigation to Inventory page after successful login', async ({ page }) => {
  // @tc:TC1217
    // Test data bound to dataset "valid_users" (representative record resolved at runtime).
    const user = getRecord("valid_users");

    // Reusing repo Page Objects: LoginPage, InventoryPage
    const loginPage = new LoginPage(page);
    const inventoryPage = new InventoryPage(page);

    // Precondition: User is successfully logged in.
    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    await loginPage.login(user.username ?? '', user.password ?? '');

    // Verify that the URL is https://www.saucedemo.com/inventory.html
    await expect(page).toHaveURL(/inventory\.html/);
    await expect(page.locator('[data-test="title"]')).toHaveText(/Products/i);
    await expect(page.locator('.inventory_item').first()).toBeVisible();

    // Check that the Inventory page elements are displayed
  });
});