import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../pages/LoginPage';

/**
 * Verify shopping cart icon visibility after login
 *
 * Test Case ID: 1218
 * Priority: P1
 * Coverage: n/a
 * Steps:
   *   1. Check for the presence of the shopping cart icon on the Inventory page
 * Expected Result: The shopping cart icon is visible.
 * Test Data: standard_user from valid_users
 * Test Data Source: dataset "valid_users" (representative record, runtime-resolved) (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com/
 */

test.describe('Verify shopping cart icon visibility after login', () => {
  test('Verify shopping cart icon visibility after login', async ({ page }) => {
  // @tc:TC1218
    // Test data bound to dataset "valid_users" (representative record resolved at runtime).
    const user = getRecord("valid_users");

    // Reusing repo Page Object: LoginPage
    const loginPage = new LoginPage(page);

    // Precondition: User is successfully logged in.
    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    await loginPage.login(user.username ?? '', user.password ?? '');
    await expect(page).toHaveURL(/inventory\.html/);

    // Check for the presence of the shopping cart icon on the Inventory page
    await expect(page.locator('[data-test="shopping-cart-link"]')).toBeVisible();
    await expect(page.locator('[data-test="title"]')).toHaveText(/Products/i);
    await expect(page.locator('.inventory_item').first()).toBeVisible();
  });
});