import { test, expect } from '@playwright/test';

/**
 * Verify login attempt with locked user account
 *
 * Test Case ID: 1220
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Navigate to https://www.saucedemo.com
   *   2. Enter locked user account username from valid_users: locked_out_user
   *   3. Enter valid password placeholder <password>
   *   4. Click the login button
 * Expected Result: An error message is displayed indicating the account is locked.
 * Test Data: locked_out_user from valid_users
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com
 */

test.describe('Verify login attempt with locked user account', () => {
  test('Verify login attempt with locked user account', async ({ page }) => {
  // @tc:TC1220
    // Navigate to https://www.saucedemo.com
    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    
    // Enter locked user account username from valid_users: locked_out_user
    await page.locator('#user-name').fill('');
    
    // Enter valid password placeholder <password>
    await page.locator('#password').fill('');
    
    // Click the login button
    await page.locator('#login-button').click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.locator('[data-test="error"]')).toBeVisible();
    await expect(page).toHaveURL('https://www.saucedemo.com');
  });
});