import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../pages/LoginPage';
import { InventoryPage } from '../pages/InventoryPage';

/**
 * Verify successful login with valid credentials
 *
 * Test Case ID: 1216
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Navigate to https://www.saucedemo.com
   *   2. Enter valid username from valid_users: standard_user
   *   3. Enter valid password placeholder <password>
   *   4. Click the login button
 * Expected Result: User is successfully logged in and redirected to the Inventory page.
 * Test Data: standard_user from valid_users
 * Test Data Source: dataset "valid_users" (representative record, runtime-resolved) (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com
 */

test.describe('Verify successful login with valid credentials', () => {
  test('Verify successful login with valid credentials', async ({ page }) => {
  // @tc:TC1216
    // Test data bound to dataset "valid_users" (representative record resolved at runtime).
    const user = getRecord("valid_users");

    // Reusing repo Page Objects: LoginPage, InventoryPage
    const loginPage = new LoginPage(page);
    const inventoryPage = new InventoryPage(page);

    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    await loginPage.login(user.username ?? '', user.password ?? '');




    // ── Verify Expected Result ──
    await expect(page).toHaveURL(/inventory\.html/);
    await expect(page.locator('[data-test="title"]')).toHaveText(/Products/i);
    await inventoryPage.verifyInventoryLoaded();
  });
});