import { test, expect } from '@playwright/test';

/**
 * Verify shopping cart icon visibility after login
 *
 * Test Case ID: 1218
 * Priority: P1
 * Coverage: n/a
 * Steps:
   *   1. Check for the presence of the shopping cart icon on the Inventory page
 * Expected Result: The shopping cart icon is visible.
 * Test Data: standard_user from valid_users
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com/
 */

test.describe('Verify shopping cart icon visibility after login', () => {
  test('Verify shopping cart icon visibility after login', async ({ page }) => {
  // @tc:TC1218
    // Check for the presence of the shopping cart icon on the Inventory page
    // NOTE: step not auto-mapped — review manually.

    // ── Verify Expected Result ──
    await expect(page).not.toHaveURL('https://www.saucedemo.com/');
  });
});