import { test, expect } from '@playwright/test';

/**
 * Verify login with empty username and password fields
 *
 * Test Case ID: 1221
 * Priority: P1
 * Coverage: n/a
 * Steps:
   *   1. Leave username field empty
   *   2. Leave password field empty
   *   3. Click the login button
 * Expected Result: An error message is displayed indicating that fields cannot be empty.
 * Test Data: empty fields
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com/
 */

test.describe('Verify login with empty username and password fields', () => {
  test('Verify login with empty username and password fields', async ({ page }) => {
  // @tc:TC1221
    // Leave username field empty
    await page.locator('#user-name').fill('');
    
    // Leave password field empty
    await page.locator('#password').fill('');
    
    // Click the login button
    await page.locator('#login-button').click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page.locator('[data-test="error"]')).toBeVisible();
    await expect(page).toHaveURL('https://www.saucedemo.com/');
  });
});