import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../pages/LoginPage';

/**
 * Verify login attempt with locked user account
 *
 * Test Case ID: 1220
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Navigate to https://www.saucedemo.com
   *   2. Enter locked user account username from valid_users: locked_out_user
   *   3. Enter valid password placeholder <password>
   *   4. Click the login button
 * Expected Result: An error message is displayed indicating the account is locked.
 * Test Data: locked_out_user from valid_users
 * Test Data Source: dataset "valid_users" → record "locked_out_user" (Test Data Store)
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com
 */

test.describe('Verify login attempt with locked user account', () => {
  test('Verify login attempt with locked user account', async ({ page }) => {
  // @tc:TC1220
    // Test data bound to dataset "valid_users", record "locked_out_user" (selected for this case).
    const user = getRecord("valid_users", "locked_out_user");

    // Reusing repo Page Object: LoginPage
    const loginPage = new LoginPage(page);

    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    await loginPage.login(user.username ?? '', user.password ?? '');




    // ── Verify Expected Result ──
    await expect(page.locator('[data-test="error"]')).toBeVisible();
    await expect(page.locator('[data-test="error"]')).toContainText('locked out');
    await expect(page).toHaveURL('https://www.saucedemo.com');
  });
});