import { test, expect } from '@playwright/test';

/**
 * Verify successful login with valid credentials
 *
 * Test Case ID: 1216
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Navigate to https://www.saucedemo.com
   *   2. Enter valid username from valid_users: standard_user
   *   3. Enter valid password placeholder <password>
   *   4. Click the login button
 * Expected Result: User is successfully logged in and redirected to the Inventory page.
 * Test Data: standard_user from valid_users
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com
 */

test.describe('Verify successful login with valid credentials', () => {
  test('Verify successful login with valid credentials', async ({ page }) => {
  // @tc:TC1216
    // Navigate to https://www.saucedemo.com
    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    
    // Enter valid username from valid_users: standard_user
    await page.locator('#user-name').fill('');
    
    // Enter valid password placeholder <password>
    await page.locator('#password').fill('');
    
    // Click the login button
    await page.locator('#login-button').click();
    await page.waitForLoadState('domcontentloaded');

    // ── Verify Expected Result ──
    await expect(page).toHaveURL(/inventory\.html/);
    await expect(page.locator('[data-test="title"]')).toHaveText(/Products/i);
  });
});