import { test, expect } from '@playwright/test';
import { getRecord } from './data/test-data';
import { LoginPage } from '../pages/LoginPage';

/**
 * Verify login attempt with invalid username
 *
 * Test Case ID: 1219
 * Priority: P0
 * Coverage: n/a
 * Steps:
   *   1. Navigate to https://www.saucedemo.com
   *   2. Enter invalid username
   *   3. Enter valid password placeholder <password>
   *   4. Click the login button
 * Expected Result: An error message is displayed indicating invalid credentials.
 * Test Data: invalid username
 *
 * Generated by LevelUp AI QA Engine (deterministic test-case build)
 * Base URL: https://www.saucedemo.com
 */

test.describe('Verify login attempt with invalid username', () => {
  test('Verify login attempt with invalid username', async ({ page }) => {
  // @tc:TC1219
    // Reusing repo Page Object: LoginPage
    const loginPage = new LoginPage(page);

    const validUser = getRecord("valid_users");
    await page.goto('https://www.saucedemo.com');
    await page.waitForLoadState('domcontentloaded');
    await loginPage.login('invalid_user', validUser.password ?? '');




    // ── Verify Expected Result ──
    await expect(page.locator('[data-test="error"]')).toBeVisible();
    await expect(page.locator('[data-test="error"]')).toContainText('do not match');
    await expect(page).toHaveURL('https://www.saucedemo.com');
  });
});